### ISSUE TITLE
google trans new not working

### ISSUE THREAD

**Issue by Priyavrat007** [lushan88a/google_trans_new#46]
it was working around one month ago. but suddenly it is showing json loading error

**Comment by Namyalg** [comment]
I am facing the same issue. The code snippet on the page doesn't work either.
Is there a fix to this issue ?

**Comment by michalis001** [comment]
not working for me either

**Comment by braindevices** [comment]
does not work at all

**Comment by erikjamesmason** [comment]
@Namyalg, can you specify your fix in google_trans_new.py?

**Comment by Namyalg** [comment]
Hi, @erikjamesmason , I followed this issue https://github.com/lushan88a/google_trans_new/issues/36, the third comment seemed to solve my problem locally

**Comment by erikjamesmason** [comment]
@Namyalg awesome, thank you very much!

**Comment by simranbhoneja** [comment]
google translator not working
It's showing this error, tried the solution given above but still the same error persists

Traceback (most recent call last):
  File "D:\PYTHON PROJECT\voice_translator.py", line 2, in <module>
    from google_trans_new import google_translator
  File "C:\Python310\lib\site-packages\google_trans_new\__init__.py", line 7, in <module>        
    from .google_trans_new import google_translator
  File "C:\Python310\lib\site-packages\google_trans_new\google_trans_new.py", line 4, in <module>
    import json, requests, random, re
ModuleNotFoundError: No module named 'requests'

Hope to get an alternative solution soon that works! Thankyou in advance :)

**Comment by nettnikl** [comment]
Hey guys, having the same problem. As a workaround, do the following:
Change line 156 in file /lib/python3.10/site-packages/google_trans_new/google_trans_new.py, (or wherever your lib is installed) from
`response = (decoded_line + ']')` 
to
`response = (decoded_line + '')`

**Comment by GbotemiB** [comment]
I also encounted the json error. it is yet to still be fixed. 

I was able to use https://github.com/nidhaloff/deep-translator to solve my problem.

**Comment by zhiying987** [comment]
> Hey guys, having the same problem. As a workaround, do the following: Change line 156 in file /lib/python3.10/site-packages/google_trans_new/google_trans_new.py, (or wherever your lib is installed) from `response = (decoded_line + ']')` to `response = (decoded_line + '')`
> 
> EDIT: Whoops, that was already recommended in the other issue, sorry.

Anaconda  do it as you sad ,but not work, can you help?

**Comment by nettnikl** [comment]
> Anaconda  do it as you sad ,but not work, can you help?

Sure, if you describe your issue further, i can see if i can help

**Comment by carolineylf** [comment]
> > Anaconda  do it as you sad ,but not work, can you help?
> 
> Sure, if you describe your issue further, i can see if i can help

Hi, when I use your method to delete ] , anaconda doesn't work. It fails to delete ].

**Comment by kwonder0926** [comment]
> 


> Hey guys, having the same problem. As a workaround, do the following: Change line 156 in file /lib/python3.10/site-packages/google_trans_new/google_trans_new.py, (or wherever your lib is installed) from `response = (decoded_line + ']')` to `response = (decoded_line + '')`
> 
> EDIT: Whoops, that was already recommended in the other issue, sorry.

Thank you. It's working now
