### ISSUE TITLE
cannot import name '__title__' from 'requests.__version__

### ISSUE THREAD

**Issue by torajx** [lushan88a/google_trans_new#47]
Hi,
I installed google_trans_new, six, requests with pip3, my python version is 3.7.7
but I get the following error:

Traceback (most recent call last):
  File "/Users/toraj/Projects/GitProjects/python/translate/app.py", line 3, in <module>
    from google_trans_new import google_translator
  File "/Users/toraj/Projects/GitProjects/python/translate/venv/lib/python3.7/site-packages/google_trans_new/__init__.py", line 7, in <module>
    from .google_trans_new import google_translator
  File "/Users/toraj/Projects/GitProjects/python/translate/venv/lib/python3.7/site-packages/google_trans_new/google_trans_new.py", line 4, in <module>
    import json, requests, random, re
  File "/Users/toraj/Projects/GitProjects/python/translate/venv/lib/python3.7/site-packages/requests/__init__.py", line 129, in <module>
    from .__version__ import __title__, __description__, __url__, __version__
ImportError: cannot import name '__title__' from 'requests.__version__' (/Users/toraj/Projects/GitProjects/python/translate/venv/lib/python3.7/site-packages/requests/__version__.py)

**Comment by torajx** [comment]
here is my sample code

from google_trans_new import google_translator


translator = google_translator()
translate_text = translator.translate('สวัสดีจีน', lang_tgt='en')
print(translate_text)
